// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `src/storage/proto/datom.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:Eavt)
pub struct Eavt {
    // message fields
    // @@protoc_insertion_point(field:Eavt.entity)
    pub entity: u64,
    // @@protoc_insertion_point(field:Eavt.attribute)
    pub attribute: u64,
    // special fields
    // @@protoc_insertion_point(special_field:Eavt.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Eavt {
    fn default() -> &'a Eavt {
        <Eavt as ::protobuf::Message>::default_instance()
    }
}

impl Eavt {
    pub fn new() -> Eavt {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "entity",
            |m: &Eavt| { &m.entity },
            |m: &mut Eavt| { &mut m.entity },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "attribute",
            |m: &Eavt| { &m.attribute },
            |m: &mut Eavt| { &mut m.attribute },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Eavt>(
            "Eavt",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Eavt {
    const NAME: &'static str = "Eavt";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.entity = is.read_uint64()?;
                },
                16 => {
                    self.attribute = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.entity != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.entity);
        }
        if self.attribute != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.attribute);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.entity != 0 {
            os.write_uint64(1, self.entity)?;
        }
        if self.attribute != 0 {
            os.write_uint64(2, self.attribute)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Eavt {
        Eavt::new()
    }

    fn clear(&mut self) {
        self.entity = 0;
        self.attribute = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Eavt {
        static instance: Eavt = Eavt {
            entity: 0,
            attribute: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Eavt {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Eavt").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Eavt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Eavt {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dsrc/storage/proto/datom.proto\"<\n\x04Eavt\x12\x16\n\x06entity\x18\
    \x01\x20\x01(\x04R\x06entity\x12\x1c\n\tattribute\x18\x02\x20\x01(\x04R\
    \tattributeJ\xa8\x02\n\x06\x12\x04\0\0\x10\x01\n\x08\n\x01\x0c\x12\x03\0\
    \0\x12\nO\n\x02\x04\0\x12\x04\n\0\x10\x012Cmessage\x20Value\x20{\n}\n\ne\
    num\x20Op\x20{\n\x20\x20OP_ADDED\x20=\x200,\n\x20\x20OP_RETRACTED\x20=\
    \x201;\n}\n\n\n\n\x03\x04\0\x01\x12\x03\n\x08\x0c\n\x0b\n\x04\x04\0\x02\
    \0\x12\x03\x0b\x02\x14\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x0b\x02\n\x0e\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0b\x02\x08\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\x0b\t\x0f\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0b\x12\x13\n\
    8\n\x04\x04\0\x02\x01\x12\x03\x0c\x02\x17\"+Value\x20value\x20=\x203;\nu\
    int64\x20tx\x20=\x204;\nOp\x20op\x20=\x205;\n\n\r\n\x05\x04\0\x02\x01\
    \x04\x12\x04\x0c\x02\x0b\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0c\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x0c\t\x12\n\x0c\n\x05\x04\
    \0\x02\x01\x03\x12\x03\x0c\x15\x16b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Eavt::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
